### ISSUE TITLE
The code sample (Quick Start) does not work, even after porting to .NET standard library

### ISSUE THREAD

**Issue by stephenhauck** [microsoftgraph/xamarin-csharp-connect-sample#25]
I did the quickstart located here https://developer.microsoft.com/en-us/graph/quick-start and it does not work.

It generates a PCL app so I converted it to .NET standard and then had to change code because what gets created uses deprecated functions in the SignOut method of AuthenticationHelper.cs.

When I run on UWP I get an error after providing the account.
<img width="490" alt="msgraph" src="https://user-images.githubusercontent.com/12648793/47991347-e7f48980-e0b7-11e8-884a-631d87d51840.PNG">

It seems that no one is keeping up with and or testing these code samples.

Has Microsoft Graph been abandoned or deprecated ?

Can I get a working example that runs with Xamarin.Forms ?

**Comment by stephenhauck** [comment]
Anyone ???

**Comment by jasonjoh** [comment]
Hi Stephen, sorry to hear you're having trouble. You're right that no one is maintaining **this** sample, but Microsoft Graph is definitely not abandoned or deprecated.

I'm in the process of creating updated materials for the different platforms, and Xamarin is on my backlog. Once that's done we'll replace the existing quick start download and archive this repo.

In the meantime, I'd recommend taking a look at this sample: https://github.com/microsoftgraph/xamarin-csharp-photosender-sample. It has been 6 months or so since I wrote that, but it does use Xamarin Forms and a .NET Standard shared library. I'm going to boot it up today and makes sure it's still in good working order.

**Comment by jasonjoh** [comment]
We're archiving this sample and redirecting folks to https://github.com/microsoftgraph/msgraph-training-xamarin (or the corresponding walkthrough at https://docs.microsoft.com/graph/tutorials/xamarin.
